# Model config
model:
  max_length: 64
  embedding_dim: 300
  num_filters: 16
  kernel_list: [3, 5, 7, 9]
  dropout: 0.5
  lin_neurons: 128
  lin_blocks: 2
  light: no
# Training config
training:
  epochs: 100
  batch_size: 128
  num_workers: 16
  half_lr: yes
  early_stop: yes
  resume: yes
  loss_weight_rescaling: yes
# Optim config
optim:
  optimiser: adam
  lr: 0.001
  weight_decay: 0.